### ISSUE TITLE
nsm: flickering hide

### ISSUE THREAD

**Issue by grammoboy2** [Stazed/seq32#8]
It looks like seq32 and seq64 has the same flickering problem as seq192 had, it hides by default, but with some flickering (it first is shown and then quickly hides at start). This is fixed in seq192 

https://github.com/jean-emmanuel/seq192/commit/be04dc6a3ae8154a3d10f828fbcfda31b5a0663d

**Comment by Stazed** [comment]
I don't mind the additional visual feedback while waiting for the NSM session to load.
Session loading works the way I want, so I do not see any reason to change it. Closing.
